# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-12 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161002_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 7, 12, 7, 1, 29, 554362, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
