# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161002_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
