# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-12 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='numero',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
