# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-12 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170712_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='numero',
        ),
    ]
